### ISSUE TITLE
Move the button to menu

### ISSUE THREAD

**Issue by andrienko** [milosh86/Brackets-ExtensionsBulkInstall#1]
Please, move the button that toggles extension installer to main menu.

Updating/bulk installing extensions is not something I do very often. So I do not really need the button for it in right side. I believe I am not the only one like that.

Probably, the button to toggle the menu would look good in "View" menu...

Thank you.

**Comment by milosh86** [comment]
Thanks for suggestion, it makes sense.

I'm not sure how quickly I can fix this, but PR is welcomed too.
